### ISSUE TITLE
Change category of existing to do tasks.

### ISSUE THREAD

**Issue by commaspace** [tokeeen/tokeeen#1]
I'm unable to change the category of a task after it's been created.  I'd have to delete it and remake the task, which seems like more work.
Additionally, it'd be convenient to be able to change the category of multiple tasks at once.

**Comment by COil** [comment]
Hi @commaspace , thanks for reporting the issue. Indeed you are right, we'll fix this ASAP.

For the batch feature, indeed it could be useful, we have to check how it could be done at the UX level. I'll open a separate ticket for this.

Thanks again, to hesitate to report other bugs or ideas of enhancement.

**Comment by COil** [comment]
Hi @commaspace , it's fixed, can you test? For now, the item is not "moved" to its new category, the page needs to be reloaded.

**Comment by commaspace** [comment]
Hi @COil, yes I was able to change the category and upon page refresh it moved to its new category.

**Comment by COil** [comment]
Closing this issue. I've made another ticket #2  for the batch feature.
